#!/bin/bash
export DISPLAY=:0
cd /home/ethos
xterm -fn 6x10 -geometry 90x40-0-0 -T "ethOS Terminal" -fa 'Monospace' -fs 10 &
failcount=0
wmctrl -a "ethOS Terminal"
while [ $? -ne 0 ]; do
  if [ "$failcount" -lt "10" ]; then
  ((failcount++))
  	sleep 1
  	wmctrl -a "ethOS Terminal"
  else
  #exit, too many failures
  	break
  fi
done
