#!/bin/bash

#Check if clinfo times out, if it does, let the user know that mining is not going to work
/opt/ethos/sbin/ethos-readconf gpucount >/dev/null
DRIVER=$(/opt/ethos/sbin/ethos-readconf driver)
NEEDAMDGPU=$(lspci -v | grep -ce Ellesmere)
if [ "$NEEDAMDGPU" = "0" ]; then
  NEEDAMDGPU=$(lspci -v | grep -ce Baffin)
fi
export DISPLAY=:0

TIMEOUT="10"
#Usb Drives need a longer timeout and a longer initial sleep.
if [ -d "/proc/scsi/usb-storage" ]; then
    TIMEOUT="45"
    sleep 10
fi
  
if [ "$DRIVER" = "fglrx" ] || [ "$DRIVER" = "amdgpu" ];then
  sleep 30
  #Set Perms
  echo -n "" > /var/run/adl_error.file
  chown ethos.ethos /var/run/adl_error.file
  echo -n "" > /var/run/ethos/wrong_driver.file
  chown ethos.ethos /var/run/ethos/wrong_driver.file

  if [ "$DRIVER" = "amdgpu" ] && [ "$NEEDAMDGPU" = "0" ];then
    ERR="WRONG DRIVER! ADD \"driver [worker] fglrx\" TO CONFIG ([worker] is 6-digit rig name)"
    echo "1" > /var/run/ethos/wrong_driver.file
    sleep 3
  elif [ "$DRIVER" = "fglrx" ] && [ "$NEEDAMDGPU" = "1" ];then
    ERR="WRONG DRIVER! ADD \"driver [worker] amdgpu\" TO CONFIG ([worker] is 6-digit rig name)"
    echo "1" > /var/run/ethos/wrong_driver.file
  fi
  timeout $TIMEOUT /usr/bin/clinfo > /dev/null

  if [ $? -ne "0" ];then
    ERR="DRIVER ERROR! POSSIBLE GPU / RISER / HARDWARE ISSUE"
    echo "1" > /var/run/adl_error.file
  fi

  if [ "$DRIVER" = "fglrx" ] && [ "$NEEDAMDGPU" = "0" ];then
    timeout $TIMEOUT /usr/local/bin/atitweak -s 
    if [ $? -ne "0" ]; then
      ERR="DRIVER ERROR! POSSIBLE GPU / RISER / HARDWARE ISSUE" 
      echo "1" > /var/run/adl_error.file
    fi
  fi
fi

if [ ! -z "$ERR" ];then
	echo "$ERR" | wall 
	echo "$ERR" >> /var/run/ethos-log.file
	echo "$ERR" >> /var/run/miner.output

fi

/opt/ethos/bin/amdmeminfo -o -s -q > /var/run/meminfo.file

