#!/bin/bash

# LICENSE AGREEMENT
#
# Version 1.2 (c) 2016 Dale Chapman, sling00@gmail.com (“Author”).
#
# By using this file, you agree to the following:
#
# This file has been licensed to gpuShack for the exclusive use and distribution as part of ethOS. All other previous licenses
# of this file have been revoked. This license does not expire and allows for any modification, distribution, and/or derivative work
# by gpuShack and by the Author. This license extends to gpuShack’s owners, operators, officers, and contractors, where
# applicable.
#
# The Author expressly forbids and revokes usage of this file, as well as any previous iterations of this file, in any
# operating system other than ethOS. Any fork of ethOS, third party or otherwise, may not use this file without express written
# permission from the Author.
#
# Personal Use
#
# End users may modify and use this script for personal use, but may not redistribute or include in a larger work, in whole, or
# in part, without express written permission from the Author.


while true; do
function DATE() {
        echo `date -u`
}
DRIVER=$(/opt/ethos/sbin/ethos-readconf runningdriver)
NEWDRIVER=$(/opt/ethos/sbin/ethos-readconf switchdriver)
if [ -z "$NEWDRIVER" ];then
  NEWDRIVER=$(/opt/ethos/sbin/ethos-readconf globaldriver)
fi
if [ "$NEWDRIVER" != "$DRIVER" ]; then
 /opt/ethos/sbin/ethos-switchdriver
fi
/opt/ethos/sbin/ethos-getcputemp
UPTIME=$(cut -d " " -f1 /proc/uptime | cut -d "." -f 1)

DAGCHANGE=$(for i in `seq 0 16`; do tail -200 /var/run/miner.$i.output; done  | grep clEnqueueNDRangeKernel | wc -l)

if [ "$DAGCHANGE" -ge "1" ]; then
	/opt/ethos/bin/minestop
	for i in `seq 0 16`; do echo "DAG CHANGE ERROR, MINERS RESTARTED" > /var/run/miner.$i.output; done  
fi
if [ "$UPTIME" -gt 3600 ]; then
HANGHAPPENED=$(dmesg | grep -c "ASIC hang happened") 
 if [ "$HANGHAPPENED" -ge "1" ]; then
  sleep 300
  echo "o" > /proc/sysrq-trigger
 fi
fi
sleep 3
done
