#!/bin/bash
# EthOS MOTD Generator
/opt/ethos/sbin/ethos-getmessage
MESSAGE=$(cat /opt/ethos/etc/message)
ETHOSVERSION=$(cat /opt/ethos/etc/version)

echo "" > /etc/motd
exec 1>> /etc/motd
echo "Welcome to ethOS $ETHOSVERSION"
echo ""
echo "$MESSAGE"
echo ""
echo "♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦"
echo " minestop:         turn off all miner instances                       "
echo " show:             show output of various log files                   "
echo " disallow:         prevent miner from starting automatically          "
echo " allow:            allow miner to start automatically                 "
echo " helpme:           show your ethOS stats panel and ethOS commands     "
echo " gethelp:          generate a diagnostics file for getting support    "
echo " hard-reboot:      issue a forced reboot                              "
echo " r:                issue a regular reboot                             "
echo "                                                                      "
echo " update:           send stats to stats panel                          "
echo " putconf:          manually put remote conf into local conf           "
echo " ethos-overclock:  force overclocks to apply from local conf          "
echo " ethos-update:     update ethOS to the latest version                 "
echo " restart-proxy:    restart local stratum proxy                        "
echo " clear-thermals:   reset thermal-related throttling back to normal    "
echo " reset-config:     reset remote/local configuration back to default   "
echo " browser:          launch web browser on local rig to stats panel     "
echo " lock:             lock the ethOS desktop                             "
echo " ethos-driver off: turn off graphics driver for the next boot         "
echo " ethos-driver on:  turn on graphics driver for the next boot          "
echo " ethoschat:        help chat (in current terminal session)            "
echo " ethoschat-local:  help chat (on rig, in seperate terminal session)   "
echo " "
echo " Knowledge Base:           http://ethosdistro.com/kb/                 "
echo " Config Documentation:     http://ethosdistro.com/pool.txt            "
echo "♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦♦"
echo ""
