#!/usr/bin/php
<?php

@ob_end_clean();

include ('/opt/ethos/lib/functions.php');

circuit_protect();
`/opt/ethos/lib/putconf.php`;
`/usr/bin/sensors | grep -Poi -m1 "(?<=\+)(.*)(?=...C\s)" > /var/run/cputemp.file`;
while(true){

        $time = time();
        $reboot_file = "/opt/ethos/etc/reboot.file";
        $number = intval(trim(file_get_contents($reboot_file)));
        $new_number = intval(get_reboot_number_from_conf());

        if(is_int($new_number) && $number < $new_number){
                $number++;
                file_put_contents($reboot_file,$number);
                `reboot -f`;
        } else {
                start_miner();
                sleep(30);
        }
}

?>
