#!/bin/bash

# LICENSE AGREEMENT
#
# Version 1.2 (c) 2016 Dale Chapman, sling00@gmail.com (“Author”).
#
# By using this file, you agree to the following:
#
# This file has been licensed to gpuShack for the exclusive use and distribution as part of ethOS. All other previous licenses
# of this file have been revoked. This license does not expire and allows for any modification, distribution, and/or derivative work
# by gpuShack and by the Author. This license extends to gpuShack’s owners, operators, officers, and contractors, where
# applicable.
#
# The Author expressly forbids and revokes usage of this file, as well as any previous iterations of this file, in any
# operating system other than ethOS. Any fork of ethOS, third party or otherwise, may not use this file without express written
# permission from the Author.
#
# Personal Use
#
# End users may modify and use this script for personal use, but may not redistribute or include in a larger work, in whole, or
# in part, without express written permission from the Author.

ATICONFIG=/usr/bin/aticonfig
NODRIVER=$(grep -c "nomine" "/proc/cmdline")
if [ -f /tmp/fglrx.configured ]
then
   echo "Not Reconfiguring X, Ati Drivers already Configured on system boot.  Delete /tmp/fglrx.configured and restart this service to force reconfiguration"
elif [ "$NODRIVER" = "1" ]; then
   echo "Booting without fglrx driver.."
   /sbin/rmmod fglrx
   echo "1" > /var/run/nomine.file
else
	rm -f /home/ethos/.Xauthority
	rm /etc/X11/xorg.conf
	if $ATICONFIG --adapter=all --initial -f --nobackup
           then
               touch /tmp/fglrx.configured
               echo "ATI Driver Configuration Successful, Starting Lightdm."
           else
	       echo "Mining Disabled: ATI Driver Configuration Failed" >> /var/run/ethos-log.file
	       echo "Mining Disabled: ATI Driver Configuration Failed" >> /var/run/miner.output
               echo '0' > /opt/ethos/etc/allow.file
        fi
fi
