#!/bin/bash

#Check if clinfo times out, if it does, let the user know that mining is not going to work
#Early GPU Count
/usr/bin/aticonfig --lsa | egrep -i 'AMD|67B1|6939|7300|Series|Supported device' | wc -l > /tmp/gpucount.file
export DISPLAY=:0
sleep 30
# Second command also gets the correct gpu count for multi-gpu per card systems, must come after X Start

timeout 10 /usr/bin/clinfo > /dev/null
if [ $? -ne "0" ]; then
	echo "WARNING: OPENCL TIMED OUT! POSSIBLE GPU / HARDWARE ISSUE" | wall
	echo "WARNING: OPENCL TIMED OUT! POSSIBLE GPU / HARDWARE ISSUE" >> /var/run/ethos-log.file
	echo "WARNING: OPENCL TIMED OUT! POSSIBLE GPU / HARDWARE ISSUE" >> /var/run/miner.output
	echo "1" > /var/run/adl_error.file
	sleep 3
	echo "WARNING: OPENCL TIMED OUT! POSSIBLE GPU / HARDWARE ISSUE" | wall
fi
timeout 10 /usr/local/bin/atitweak -s | grep -Po "(^\d+)(?=.)" | wc -l > /tmp/gpucount.file
if [ $? -ne "0" ]; then
        echo "WARNING: AMD ADL INTERFACE ERRORED/TIMED OUT! POSSIBLE GPU / HARDWARE ISSUE" | wall
	echo "WARNING: AMD ADL INTERFACE ERRORED/TIMED OUT! POSSIBLE GPU / HARDWARE ISSUE" >> /var/run/ethos-log.file
        echo "WARNING: AMD ADL INTERFACE ERRORED/TIMED OUT! POSSIBLE GPU / HARDWARE ISSUE" >> /var/run/miner.output
        echo "1" > /var/run/adl_error.file
	sleep 3
        echo "WARNING: AMD ADL INTERFACE ERRORED/TIMED OUT! POSSIBLE GPU / HARDWARE ISSUE" | wall
      
fi
/opt/ethos/bin/amdmeminfo -o -s -q > /var/run/meminfo.file

