#!/bin/bash

#Check if clinfo times out, if it does, let the user know that mining is not going to work
/opt/ethos/sbin/ethos-readconf gpucount >/dev/null
DRIVER=$(/opt/ethos/sbin/ethos-readconf driver)
NEEDAMDGPU=$(lspci -v | egrep -ice 'ellesmere|baffin')
AMDCOUNT=$(lspci -nv | egrep -c "0300: 1002|0380: 1002")
export DISPLAY=:0 2>&1>/dev/null

TIMEOUT="25"
#Usb Drives need a longer timeout and a longer initial sleep.
if [ -d "/proc/scsi/usb-storage" ]; then
    TIMEOUT="45"
    sleep 10
fi
  
if [ "$DRIVER" = "fglrx" ] || [ "$DRIVER" = "amdgpu" ];then
  sleep 30

  if [ "$DRIVER" = "amdgpu" ] && [ "$NEEDAMDGPU" = "0" ] && [ "$AMDCOUNT" -ge "1" ];then
    ERR="WRONG DRIVER! ADD \"driver [worker] fglrx\" TO CONFIG ([worker] is 6-digit rig name)"
    echo "1" > /var/run/ethos/wrong_driver.file
    sleep 3
  elif [ "$DRIVER" = "fglrx" ] && [ "$NEEDAMDGPU" -ge "1" ] && [ "$AMDCOUNT" -ge "1" ];then
    ERR="WRONG DRIVER! ADD \"driver [worker] amdgpu\" TO CONFIG ([worker] is 6-digit rig name)"
    echo "1" > /var/run/ethos/wrong_driver.file
  elif [ "$AMDCOUNT" = "0" ]; then
    ERR="NO MINING GPUS DETECTED - Check risers and power cables"
  fi
  
  if [ -z "$ERR" ];then
  timeout $TIMEOUT /usr/bin/clinfo > /dev/null
  fi
  if [ $? -ne "0" ];then
    ERR="DRIVER ERROR! POSSIBLE GPU / RISER / HARDWARE ISSUE"
    echo "1" > /var/run/ethos/adl_error.file
  fi

  if [ "$DRIVER" = "fglrx" ] && [ "$NEEDAMDGPU" = "0" ];then
    timeout $TIMEOUT /usr/local/bin/atitweak -s 
    if [ $? -ne "0" ]; then
      ERR="DRIVER ERROR! POSSIBLE GPU / RISER / HARDWARE ISSUE" 
      echo "1" > /var/run/ethos/adl_error.file
    fi
  fi
fi

if [ ! -z "$ERR" ];then
	echo "$ERR" | wall 
fi


