#!/usr/bin/php
<?php

@ob_end_clean();

require_once('/opt/ethos/lib/functions.php');
require_once('/opt/ethos/lib/minerprocess.php');
check_status();
$uptime = trim(`cut -d " " -f1 /proc/uptime | cut -d "." -f 1`);
if ($uptime < 300) {
	$sleep = mt_rand(5, 59);
	file_put_contents("/var/run/ethos/sleep.file", $sleep);
	check_status();
	sleep($sleep);
	file_put_contents("/var/run/ethos/sleep.file", "0");
}
`/opt/ethos/sbin/ethos-getcputemp`;
while(true){

        $time = time();
        $reboot_file = "/opt/ethos/etc/reboot.file";
        $number = intval(trim(file_get_contents($reboot_file)));
        $new_number = intval(get_reboot_number_from_conf());

        if(is_int($new_number) && $number < $new_number){
                $number++;
                file_put_contents($reboot_file,$number);
                `sudo reboot`;
        } else {
		start_miner();
                sleep(5);
        }
}

?>
