#!/bin/bash
#/opt/ethos/bin/minertimer "Miner Startup - Up to 5 minutes" 5 &
if [ -e "/home/ethos/custom.sh" ]; then
  /home/ethos/custom.sh
fi
 /opt/ethos/sbin/urlconfig
LOCKSCREEN=$(/opt/ethos/sbin/ethos-readconf lockscreen)
if [ ! -z "$LOCKSCREEN" ]; then
  if [ "$LOCKSCREEN" = "enabled" ];then
    sleep 10
    /opt/ethos/bin/lock
  fi
fi

echo "0" > /var/run/ethos/prelogin.file 
