#!/usr/bin/env php
<?php

@ob_end_clean();

require_once('/opt/ethos/lib/functions.php');
$update = $argv[1];
if ( $update == "update.php" ) {
  $log = send_data();
  require_once('/opt/ethos/lib/ethos-stats-dump.php');
  echo "Sent updated stats to webhook.\n";
  exit ();
}

while(true){
        require_once("/opt/ethos/bin/hash-monitor");
        $log = send_data();
	file_put_contents("/var/run/ethos/stats.file",$log);
        sleep(120);
}

?>
