#!/bin/bash
export DISPLAY=:0
CONF=/home/ethos/local.conf


GPUDATA=/var/run/gpudata.file

# DO NOT refresh GPU data every time this script is run.
# When a GPU locks up, this will cause ethos-readconf to freeze up permanently,
# which means all apps will cease to function, even those that do not need
# any info about the GPUs to function.
refresh_gpu_data() {
    GPUDATAAGE=`echo "$((\`date +%s\` - \`stat -L --format %Y $GPUDATA\`))"`
    if [ -f "$GPUDATA" ] && [ "$GPUDATAAGE" -ge "30" ] || [ -z "$GPUDATA" ]; then
        atitweak -s > /var/run/gpudata.file
    fi
}


	case $1 in
		core )
    		refresh_gpu_data
			CORE=`grep -Po '(?<=engine.clock.)([0-9]*\.?[0-9]*.)(?=MHz,)' "$GPUDATA"`
			echo "$CORE"
		;;
 		fan )
    		refresh_gpu_data
			FAN=`grep -Po '(?<=fan speed.)(\d+)(?=%)' "$GPUDATA"`
			echo "$FAN"
 		;;
 		fanrpm )
    		refresh_gpu_data
			FANRPM=`grep -Po '(?<=\%.\()(\w+)(?=.RPM)' "$GPUDATA"`
			echo "$FANRPM"
		;;
		fullpool )
			FULLPOOL=$(grep -Po '\s*(?<=^pool\s)(.*)' "$CONF")
			echo "$FULLPOOL"
 		;;
		flags )
			GLOBALFLAGS=`grep -Po '\s*(?<=^flags\s)(.*)' "$CONF"`
			echo "$GLOBALFLAGS"
		;;
		loc )
			LOC=`grep -Po "\s*(?<=^loc."$HOSTNAME"\s)(.*)" "$CONF"`
			echo "$LOC"
		;;
		maxtemp )
			MAXGPUTEMP=`grep -Po "\s*(?<=^mxt."$HOSTNAME"\s)(.*)" "$CONF"`
			echo "$MAXGPUTEMP"
		;;
		globalmaxtemp )
			MAXGPUTEMP=`grep -Po '\s*(?<=^maxgputemp\s)(.*)' "$CONF"`
			echo "$MAXGPUTEMP"
		;;
		mem )
    		refresh_gpu_data
			MEMORY=`grep -Po '(?<=memory.clock.)(\d+)(?=MHz,)' "$GPUDATA"`
			echo "$MEMORY"
		;;
		pool )
			POOL=$(grep -Po '\s*(?<=^pool\s)(.*)' "$CONF" | cut -d "/" -f 3)
			echo "$POOL"
 		;;
		powertune )
    		refresh_gpu_data
			POWERTUNE=`grep -Po '(?<=powertune.)(\d+)(?=%)' "$GPUDATA"`
			echo "$POWERTUNE"
		;;
		proxypool1 )
			PROXYPOOL1=`grep -Po '\s*(?<=^proxypool1\s)(.*)' "$CONF"`
			echo "$PROXYPOOL1"
		;;
		proxypool2 )
            PROXYPOOL2=`grep -Po '\s*(?<=^proxypool2\s)(.*)' "$CONF"`
            echo "$PROXYPOOL2"
		;;
		proxypool3 )
            PROXYPOOL2=`grep -Po '\s*(?<=^proxypool3\s)(.*)' "$CONF"`
            echo "$PROXYPOOL3"
		;;
		proxypool4 )
            PROXYPOOL2=`grep -Po '\s*(?<=^proxypool4\s)(.*)' "$CONF"`
            echo "$PROXYPOOL4"
		;;
		proxywallet )
			STRATUMWALLET=`grep -Po '\s*(?<=^proxywallet\s)(.*)' "$CONF"`
            echo "$STRATUMWALLET"
		;;
		reboots )
			REBOOTS=`grep -Po "\s*(?<=^reb."$HOSTNAME"\s)(.*)" "$CONF"`
 			echo "$REBOOTS"
 		;;
		reporturl )
			REPORTURL=`grep -Po '\s*(?<=^reporturl\s)\s*((?:http.|https.)).*' "$CONF"`
			echo "$REPORTURL"
		;;
		rigflags )
			RIGFLAGS=`grep -Po "\s*(?<=^flg."$HOSTNAME"\s)(.*)" "$CONF"`
			echo "$RIGFLAGS"
		;;
		selectedgpus )
			SELECTEDGPUS=`grep -Po "\s*(?<=^sel."$HOSTNAME"\s)(.*)" "$CONF"`
			echo "$SELECTEDGPUS"
		;;
		stratumenabled )
			STRATUMENABLED=`grep "stratumproxy" "$CONF" | grep -v "#" | cut -d " " -f 2`
			echo "$STRATUMENABLED"
		;;
		temps )
    		refresh_gpu_data
			TEMPS=`grep -Po '(?<=temperature.)(\d+)(?= C)' "$GPUDATA"`
			echo "$TEMPS"
		;;
		voltage )
    		refresh_gpu_data
			VOLTAGE=`grep -Po "(?<=core voltage.)(.*)(?=VDC)" "$GPUDATA"`
			echo "$VOLTAGE"
		;;
        autoreboot )
            NAME=$1
            VALUE=`grep -Poi "\s*(?<=autoreboot)\s+(\d+|true|false)" "$CONF"`
            echo "$VALUE"
        ;;
        custompanel )
            VALUE=`grep -Poi "\s*(?<=custompanel)\s+(.*)" "$CONF"`
            echo "$VALUE"
        ;;
		* )
		echo "Usage:"

		echo "fullpool - returns full pool url"
		echo "flags - return miner configuration flags"
		echo "globalmaxtemp - return global max gpu temperature"
		echo "rigflags - return rig specific miner flags"
		echo "core - return running gpu core clocks"
		echo "mem - return running gpu mem clocks"
		echo "fan - return running gpu fan speeds"
		echo "pool - return pool data"
		echo "powertune - return powertune setting"
		echo "reboots - return the number of reboots the host has been issued via server reb string"
		echo "reporturl - returns the url to send stats to"
		echo "maxtemp - return gpu overheat temperature threshold"
		echo "selectedgpus - returns gpus selected for mining"
		echo "stratumenabled - return whether to use local stratum proxy or not"
		echo "proxypool1 - return proxypool 1 details"
		echo "proxypool2 - return proxypool 2 details"
		echo "proxywallet - return stratum proxy wallet address"
		echo "temps - return GPU temperatures"
		echo "voltage - return running gpu voltage"
		echo "autoreboot - If the system locks up and stops hashing, auto-reboot? true|false [Default: false]"
		echo "custompanel - A specific private farm ID to replace the random-based-on-public-IP value. [Default: null]"
		exit 1
		;;
	esac
